/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rocket_orbiting_moon.glb 
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-orbiting-moon-c613bee6fbd041e58a35d777ae87bdcb
Title: Rocket Orbiting Moon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocket_orbiting_moon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ring_1_Ring_0.geometry} material={materials.Ring} position={[-160.696, 8.557, 70.844]} rotation={[-1.546, -0.884, 2.545]} scale={1.022} />
      <mesh geometry={nodes.Raket_1_Raket_0.geometry} material={materials.Raket} position={[0, -59.286, 0]} rotation={[0, 1.236, 0]} />
      <mesh geometry={nodes.Subdivision_Surface_Subdivision_Surface1_0.geometry} material={materials['Subdivision_Surface.1']} position={[6.23, 27.455, 6.83]} rotation={[0.015, -0.11, -2.157]} />
    </group>
  )
}

useGLTF.preload('/rocket_orbiting_moon.glb')
